### PR TITLE
Adding $ as valid value

### PR DESCRIPTION
**Pull request by alebon**

### CODE REVIEW

**Comment by jacobchristensen79** [comment]
We need this as currently there is no other way to filter/search by referenced values. We store $ref or $id to link to fx user.group.$id so to know what user are in a group we can filter by .$id using rql.
Thanks.

**Comment by mrix** [comment]
Hi @alebon and @jacobchristensen79 .

This is not a [standart behavior](http://dundalek.com/rql/draft-zyp-rql-00.html#anchor31). I won't merge it.
`Late static binding` is used in `Lexer` class. You can extend `Lexer` class and override `Lexer::REGEX_VALUE` value in Graviton RQL library. But I really don't understand how it can help. Percent-encoded values are decoded on lexing step.

**Comment by jacobchristensen79** [comment]
No, simbol $ is not matched against the regex and in step processConstant it will go straight into a SyntaxErrorException. So will try to Extend class.

**Comment by alebon** [comment]
Ok

**Pull request closed without merging**
